// <auto-generated />
namespace DartsConsole.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Addthrownumtotablegameline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addthrownumtotablegameline));
        
        string IMigrationMetadata.Id
        {
            get { return "201407011755440_Add throw num to table game line"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
