// <auto-generated />
namespace DartsConsole.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Changewinnertoteam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changewinnertoteam));
        
        string IMigrationMetadata.Id
        {
            get { return "201406251743518_Change winner to team"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
